// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package tracing_service

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfConnectEvent struct {
	_                    structs.HostLayout
	TimestampNs          uint64
	UserId               uint32
	GroupId              uint32
	ProcessId            uint32
	ParentProcessId      uint32
	ProcessTitle         [16]uint8
	_                    [8]byte
	SourceAddress        [16]byte /* uint128 */
	DestinationAddress   [16]byte /* uint128 */
	SourcePort           uint16
	DestinationPort      uint16
	AddressFamily        uint16
	TransportProtocol    uint8
	ExecutableName       [256]uint8
	CommandLine          [256]uint8
	ParentExecutableName [256]uint8
	ParentCommandLine    [256]uint8
	_                    [9]byte
}

type BpfConnectLatencyEvent struct {
	_                  structs.HostLayout
	TimestampNs        uint64
	DurationNs         uint64
	UserId             uint32
	GroupId            uint32
	ProcessId          uint32
	ParentProcessId    uint32
	ProcessTitle       [16]uint8
	SourceAddress      [16]byte /* uint128 */
	DestinationAddress [16]byte /* uint128 */
	SourcePort         uint16
	DestinationPort    uint16
	AddressFamily      uint16
	_                  [10]byte
}

type BpfConnectStartInfo struct {
	_               structs.HostLayout
	TimestampNs     uint64
	UserId          uint32
	GroupId         uint32
	ProcessId       uint32
	ParentProcessId uint32
	ProcessTitle    [16]uint8
}

type BpfDestroyConnectionEvent struct {
	_                   structs.HostLayout
	TimestampNs         uint64
	_                   [8]byte
	SourceAddress       [16]byte /* uint128 */
	DestinationAddress  [16]byte /* uint128 */
	SourcePort          uint16
	DestinationPort     uint16
	AddressFamily       uint16
	TransportProtocol   uint8
	_                   [1]byte
	ConntrackStatusMask uint32
	Timeout             uint32
	Start               uint64
	Stop                uint64
	TcpState            uint8
	TcpLastDirection    uint8
	_                   [6]byte
	SourcePackets       uint64
	SourceBytes         uint64
	DestinationPackets  uint64
	DestinationBytes    uint64
	_                   [8]byte
}

type BpfExecveEvent struct {
	_                    structs.HostLayout
	TimestampNs          uint64
	UserId               uint32
	GroupId              uint32
	ProcessId            uint32
	ParentProcessId      uint32
	ProcessTitle         [16]uint8
	Filename             [1024]uint8
	Argv                 [32][1024]uint8
	Argc                 uint32
	ParentExecutableName [256]uint8
	ParentCommandLine    [256]uint8
	_                    [4]byte
}

type BpfFileOpenEvent struct {
	_               structs.HostLayout
	TimestampNs     uint64
	UserId          uint32
	GroupId         uint32
	ProcessId       uint32
	ParentProcessId uint32
	ProcessTitle    [16]uint8
	Filename        [256]uint8
	Flags           int32
	Mode            int32
}

type BpfPacketDropEvent struct {
	_                  structs.HostLayout
	TimestampNs        uint64
	Reason             uint16
	_                  [6]byte
	Location           uint64
	_                  [8]byte
	SourceAddress      [16]byte /* uint128 */
	DestinationAddress [16]byte /* uint128 */
	SourcePort         uint16
	DestinationPort    uint16
	AddressFamily      uint16
	TransportProtocol  uint8
	_                  [9]byte
}

type BpfTcpErrorEvent struct {
	_                  structs.HostLayout
	TimestampNs        uint64
	_                  [8]byte
	SourceAddress      [16]byte /* uint128 */
	DestinationAddress [16]byte /* uint128 */
	SourcePort         uint16
	DestinationPort    uint16
	AddressFamily      uint16
	State              uint16
	Err                int32
	_                  [4]byte
}

type BpfTcpIcmpErrorEvent struct {
	_                  structs.HostLayout
	TimestampNs        uint64
	_                  [8]byte
	SourceAddress      [16]byte /* uint128 */
	DestinationAddress [16]byte /* uint128 */
	SourcePort         uint16
	DestinationPort    uint16
	AddressFamily      uint16
	IcmpType           uint8
	IcmpCode           uint8
	Info               uint32
	_                  [4]byte
}

type BpfTcpResetEvent struct {
	_                  structs.HostLayout
	TimestampNs        uint64
	_                  [8]byte
	SourceAddress      [16]byte /* uint128 */
	DestinationAddress [16]byte /* uint128 */
	SourcePort         uint16
	DestinationPort    uint16
	AddressFamily      uint16
	State              uint16
	_                  [8]byte
}

type BpfTcpRetransmissionEvent struct {
	_                  structs.HostLayout
	TimestampNs        uint64
	_                  [8]byte
	SourceAddress      [16]byte /* uint128 */
	DestinationAddress [16]byte /* uint128 */
	SourcePort         uint16
	DestinationPort    uint16
	AddressFamily      uint16
	State              uint16
	_                  [8]byte
}

type BpfTcpRetransmissionSynackEvent struct {
	_                  structs.HostLayout
	TimestampNs        uint64
	_                  [8]byte
	SourceAddress      [16]byte /* uint128 */
	DestinationAddress [16]byte /* uint128 */
	SourcePort         uint16
	DestinationPort    uint16
	AddressFamily      uint16
	_                  [10]byte
}

type BpfTcpSetStateEvent struct {
	_                  structs.HostLayout
	TimestampNs        uint64
	_                  [8]byte
	SourceAddress      [16]byte /* uint128 */
	DestinationAddress [16]byte /* uint128 */
	SourcePort         uint16
	DestinationPort    uint16
	AddressFamily      uint16
	OldState           uint16
	NewState           uint16
	_                  [6]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapConnectEvents                 = "connect_events"
	bpfMapConnectLatencyEvents          = "connect_latency_events"
	bpfMapConnectStartInfos             = "connect_start_infos"
	bpfMapDestroyConnectionEvents       = "destroy_connection_events"
	bpfMapExecveEvents                  = "execve_events"
	bpfMapFileOpenEvents                = "file_open_events"
	bpfMapPacketDropEvents              = "packet_drop_events"
	bpfMapPacketDropReasonFilter        = "packet_drop_reason_filter"
	bpfMapTcpErrorEvents                = "tcp_error_events"
	bpfMapTcpIcmpErrorEvents            = "tcp_icmp_error_events"
	bpfMapTcpResetEvents                = "tcp_reset_events"
	bpfMapTcpRetransmissionEvents       = "tcp_retransmission_events"
	bpfMapTcpRetransmissionSynackEvents = "tcp_retransmission_synack_events"
	bpfMapTcpSetStateEvents             = "tcp_set_state_events"
	bpfProgEnterExecve                  = "enter_execve"
	bpfProgNfCtHelperDestroy            = "nf_ct_helper_destroy"
	bpfProgTcpConnect                   = "tcp_connect"
	bpfProgTcpDoneWithError             = "tcp_done_with_error"
	bpfProgTcpFinishConnect             = "tcp_finish_connect"
	bpfProgTcpReset                     = "tcp_reset"
	bpfProgTcpRetransmitSkb             = "tcp_retransmit_skb"
	bpfProgTcpRetransmitSynack          = "tcp_retransmit_synack"
	bpfProgTcpV4Err                     = "tcp_v4_err"
	bpfProgTcpV6Err                     = "tcp_v6_err"
	bpfProgTraceInetSockSetState        = "trace_inet_sock_set_state"
	bpfProgTraceKfreeSkb                = "trace_kfree_skb"
	bpfProgTraceOpenat                  = "trace_openat"
	bpfVarUnused                        = "unused"
	bpfVarUnused2                       = "unused2"
	bpfVarUnused4                       = "unused4"
	bpfVarUnused5                       = "unused5"
	bpfVarUnused6                       = "unused6"
	bpfVarUnused7                       = "unused7"
	bpfVarUnusedConnectLatencyEvent     = "unused_connect_latency_event"
	bpfVarUnusedFileOpenEvent           = "unused_file_open_event"
	bpfVarUnusedTcpErrorEvent           = "unused_tcp_error_event"
	bpfVarUnusedTcpIcmpErrorEvent       = "unused_tcp_icmp_error_event"
	bpfVarUnusedTcpResetEvent           = "unused_tcp_reset_event"
	bpfVarUnusedTcpSetStateEvent        = "unused_tcp_set_state_event"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	EnterExecve           *ebpf.ProgramSpec `ebpf:"enter_execve"`
	NfCtHelperDestroy     *ebpf.ProgramSpec `ebpf:"nf_ct_helper_destroy"`
	TcpConnect            *ebpf.ProgramSpec `ebpf:"tcp_connect"`
	TcpDoneWithError      *ebpf.ProgramSpec `ebpf:"tcp_done_with_error"`
	TcpFinishConnect      *ebpf.ProgramSpec `ebpf:"tcp_finish_connect"`
	TcpReset              *ebpf.ProgramSpec `ebpf:"tcp_reset"`
	TcpRetransmitSkb      *ebpf.ProgramSpec `ebpf:"tcp_retransmit_skb"`
	TcpRetransmitSynack   *ebpf.ProgramSpec `ebpf:"tcp_retransmit_synack"`
	TcpV4Err              *ebpf.ProgramSpec `ebpf:"tcp_v4_err"`
	TcpV6Err              *ebpf.ProgramSpec `ebpf:"tcp_v6_err"`
	TraceInetSockSetState *ebpf.ProgramSpec `ebpf:"trace_inet_sock_set_state"`
	TraceKfreeSkb         *ebpf.ProgramSpec `ebpf:"trace_kfree_skb"`
	TraceOpenat           *ebpf.ProgramSpec `ebpf:"trace_openat"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	ConnectEvents                 *ebpf.MapSpec `ebpf:"connect_events"`
	ConnectLatencyEvents          *ebpf.MapSpec `ebpf:"connect_latency_events"`
	ConnectStartInfos             *ebpf.MapSpec `ebpf:"connect_start_infos"`
	DestroyConnectionEvents       *ebpf.MapSpec `ebpf:"destroy_connection_events"`
	ExecveEvents                  *ebpf.MapSpec `ebpf:"execve_events"`
	FileOpenEvents                *ebpf.MapSpec `ebpf:"file_open_events"`
	PacketDropEvents              *ebpf.MapSpec `ebpf:"packet_drop_events"`
	PacketDropReasonFilter        *ebpf.MapSpec `ebpf:"packet_drop_reason_filter"`
	TcpErrorEvents                *ebpf.MapSpec `ebpf:"tcp_error_events"`
	TcpIcmpErrorEvents            *ebpf.MapSpec `ebpf:"tcp_icmp_error_events"`
	TcpResetEvents                *ebpf.MapSpec `ebpf:"tcp_reset_events"`
	TcpRetransmissionEvents       *ebpf.MapSpec `ebpf:"tcp_retransmission_events"`
	TcpRetransmissionSynackEvents *ebpf.MapSpec `ebpf:"tcp_retransmission_synack_events"`
	TcpSetStateEvents             *ebpf.MapSpec `ebpf:"tcp_set_state_events"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
	Unused                    *ebpf.VariableSpec `ebpf:"unused"`
	Unused2                   *ebpf.VariableSpec `ebpf:"unused2"`
	Unused4                   *ebpf.VariableSpec `ebpf:"unused4"`
	Unused5                   *ebpf.VariableSpec `ebpf:"unused5"`
	Unused6                   *ebpf.VariableSpec `ebpf:"unused6"`
	Unused7                   *ebpf.VariableSpec `ebpf:"unused7"`
	UnusedConnectLatencyEvent *ebpf.VariableSpec `ebpf:"unused_connect_latency_event"`
	UnusedFileOpenEvent       *ebpf.VariableSpec `ebpf:"unused_file_open_event"`
	UnusedTcpErrorEvent       *ebpf.VariableSpec `ebpf:"unused_tcp_error_event"`
	UnusedTcpIcmpErrorEvent   *ebpf.VariableSpec `ebpf:"unused_tcp_icmp_error_event"`
	UnusedTcpResetEvent       *ebpf.VariableSpec `ebpf:"unused_tcp_reset_event"`
	UnusedTcpSetStateEvent    *ebpf.VariableSpec `ebpf:"unused_tcp_set_state_event"`
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	ConnectEvents                 *ebpf.Map `ebpf:"connect_events"`
	ConnectLatencyEvents          *ebpf.Map `ebpf:"connect_latency_events"`
	ConnectStartInfos             *ebpf.Map `ebpf:"connect_start_infos"`
	DestroyConnectionEvents       *ebpf.Map `ebpf:"destroy_connection_events"`
	ExecveEvents                  *ebpf.Map `ebpf:"execve_events"`
	FileOpenEvents                *ebpf.Map `ebpf:"file_open_events"`
	PacketDropEvents              *ebpf.Map `ebpf:"packet_drop_events"`
	PacketDropReasonFilter        *ebpf.Map `ebpf:"packet_drop_reason_filter"`
	TcpErrorEvents                *ebpf.Map `ebpf:"tcp_error_events"`
	TcpIcmpErrorEvents            *ebpf.Map `ebpf:"tcp_icmp_error_events"`
	TcpResetEvents                *ebpf.Map `ebpf:"tcp_reset_events"`
	TcpRetransmissionEvents       *ebpf.Map `ebpf:"tcp_retransmission_events"`
	TcpRetransmissionSynackEvents *ebpf.Map `ebpf:"tcp_retransmission_synack_events"`
	TcpSetStateEvents             *ebpf.Map `ebpf:"tcp_set_state_events"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.ConnectEvents,
		m.ConnectLatencyEvents,
		m.ConnectStartInfos,
		m.DestroyConnectionEvents,
		m.ExecveEvents,
		m.FileOpenEvents,
		m.PacketDropEvents,
		m.PacketDropReasonFilter,
		m.TcpErrorEvents,
		m.TcpIcmpErrorEvents,
		m.TcpResetEvents,
		m.TcpRetransmissionEvents,
		m.TcpRetransmissionSynackEvents,
		m.TcpSetStateEvents,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
	Unused                    *ebpf.Variable `ebpf:"unused"`
	Unused2                   *ebpf.Variable `ebpf:"unused2"`
	Unused4                   *ebpf.Variable `ebpf:"unused4"`
	Unused5                   *ebpf.Variable `ebpf:"unused5"`
	Unused6                   *ebpf.Variable `ebpf:"unused6"`
	Unused7                   *ebpf.Variable `ebpf:"unused7"`
	UnusedConnectLatencyEvent *ebpf.Variable `ebpf:"unused_connect_latency_event"`
	UnusedFileOpenEvent       *ebpf.Variable `ebpf:"unused_file_open_event"`
	UnusedTcpErrorEvent       *ebpf.Variable `ebpf:"unused_tcp_error_event"`
	UnusedTcpIcmpErrorEvent   *ebpf.Variable `ebpf:"unused_tcp_icmp_error_event"`
	UnusedTcpResetEvent       *ebpf.Variable `ebpf:"unused_tcp_reset_event"`
	UnusedTcpSetStateEvent    *ebpf.Variable `ebpf:"unused_tcp_set_state_event"`
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	EnterExecve           *ebpf.Program `ebpf:"enter_execve"`
	NfCtHelperDestroy     *ebpf.Program `ebpf:"nf_ct_helper_destroy"`
	TcpConnect            *ebpf.Program `ebpf:"tcp_connect"`
	TcpDoneWithError      *ebpf.Program `ebpf:"tcp_done_with_error"`
	TcpFinishConnect      *ebpf.Program `ebpf:"tcp_finish_connect"`
	TcpReset              *ebpf.Program `ebpf:"tcp_reset"`
	TcpRetransmitSkb      *ebpf.Program `ebpf:"tcp_retransmit_skb"`
	TcpRetransmitSynack   *ebpf.Program `ebpf:"tcp_retransmit_synack"`
	TcpV4Err              *ebpf.Program `ebpf:"tcp_v4_err"`
	TcpV6Err              *ebpf.Program `ebpf:"tcp_v6_err"`
	TraceInetSockSetState *ebpf.Program `ebpf:"trace_inet_sock_set_state"`
	TraceKfreeSkb         *ebpf.Program `ebpf:"trace_kfree_skb"`
	TraceOpenat           *ebpf.Program `ebpf:"trace_openat"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.EnterExecve,
		p.NfCtHelperDestroy,
		p.TcpConnect,
		p.TcpDoneWithError,
		p.TcpFinishConnect,
		p.TcpReset,
		p.TcpRetransmitSkb,
		p.TcpRetransmitSynack,
		p.TcpV4Err,
		p.TcpV6Err,
		p.TraceInetSockSetState,
		p.TraceKfreeSkb,
		p.TraceOpenat,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed packet_logging_bpf_bpfel.o
var _BpfBytes []byte
